name: Auto Merge Approved Pull Requests

on:
  pull_request:
    types:
      - closed # Trigger when a pull request is closed (e.g., merged manually).
      - review_requested
      - labeled
      - ready_for_review

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR State
        if: ${{ github.event.pull_request.merged == true }} # Proceed only if the PR is merged.
        run: |
          echo "PR merged successfully. Automating commit or tagging."
